### ISSUE TITLE
Secure Connection to sonar qube or cloud with token has missing handler.

### ISSUE THREAD

**Issue by jpalmonacid** [asmodeus812/coc-sonarlint#6]
Hi,
Thanks for this coc plugin. Really appreciate it. Please, this probably may not be an issue but a misconfiguration from my part, so I'd like to ask you for help. 

## Environment
`:CocInfo` output:
```
vim version: VIM - Vi IMproved 9.0 9001392
node version: v20.3.0
coc.nvim version: 0.0.82-9fd85781 2024-09-21 00:59:00 +0900
coc.nvim directory: /home/jpalmonacid/.local/src/dotvim/bundle/coc.nvim
term: tmux
platform: linux
```

## Problem
I'm trying to configure `coc-sonarlint` in connected mode and I'm getting the following error as you may see in Sonar Lint output:
```
[Error - 12:12:46.697] Can't get token for server https://some-corporate-server-url.com
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Unhandled method sonarlint/getTokenForServer
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at org.sonarsource.sonarlint.ls.settings.SettingsManager.getTokenFromClient(SettingsManager.java:404)
	at org.sonarsource.sonarlint.ls.settings.SettingsManager.lambda$parseSonarQubeConnections$11(SettingsManager.java:378)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.sonarsource.sonarlint.ls.settings.SettingsManager.parseSonarQubeConnections(SettingsManager.java:374)
	at org.sonarsource.sonarlint.ls.settings.SettingsManager.parseServerConnections(SettingsManager.java:351)
	at org.sonarsource.sonarlint.ls.settings.SettingsManager.parseSettings(SettingsManager.java:333)
	at org.sonarsource.sonarlint.ls.settings.SettingsManager.lambda$didChangeConfiguration$3(SettingsManager.java:177)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Unhandled method sonarlint/getTokenForServer
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	... 3 more
```
This is what I have in my global `coc-settings.json` file:
```json
  "sonarlint.ls.javaHome": "/usr/lib/jvm/java-21-openjdk-amd64",
  "sonarlint.connectedMode.connections.sonarqube": [
      {
          "serverUrl": "https://some-corporate-server-url.com",
          "token": "<generated-user-token-from-sonarqube-server>"
      }
  ]
```
Please, let me know if I can add any more info.
Thank you!

**Comment by asmodeus812** [comment]
The connected mode was never ported from the original extension, that is why. I will check it out to see how easy it is, however i have no running setup to test with, do you know of some sort of public cloud instance of sonar that can be used ?

**Comment by asmodeus812** [comment]
@jpalmonacid can you pull the new version 0.0.18, and check it out ? Seems like the token handler was missing, i did mange to connect to a public cloud server from here - https://[sonarcloud.io/api/components/search_projects?boostNewProjects=false&facets=ncloc%2Clanguages&p=2&ps=50&f=analysisDate&s=analysisDate&asc=false](https://sonarcloud.io/api/components/search_projects?boostNewProjects=false&facets=ncloc%2Clanguages&p=2&ps=50&f=analysisDate&s=analysisDate&asc=false)

```json
    "sonarlint.connectedMode.connections.sonarcloud": [
        {
            "organizationKey": "googleapis",
            "connectionId": "google-apis"
        }
    ],
```

**Comment by jpalmonacid** [comment]
> @jpalmonacid can you pull the new version 0.0.18, and check it out ? Seems like the token handler was missing, i did mange to connect to a public cloud server from here - https://[sonarcloud.io/api/components/search_projects?boostNewProjects=false&facets=ncloc%2Clanguages&p=2&ps=50&f=analysisDate&s=analysisDate&asc=false](https://sonarcloud.io/api/components/search_projects?boostNewProjects=false&facets=ncloc%2Clanguages&p=2&ps=50&f=analysisDate&s=analysisDate&asc=false)
> 
> ```json
>     "sonarlint.connectedMode.connections.sonarcloud": [
>         {
>             "organizationKey": "googleapis",
>             "connectionId": "google-apis"
>         }
>     ],
> ```
I can't thank you enough for this prompt fix. It's working correctly now 🎉. Sorry I didn't answer you in a timely manner.
Here's what I see in the logs:
```
...
[Debug - 15:07:18.706] GET 200 https://<some-corporate-server-url.com>/api/system/status | response time=771ms
[Debug - 15:07:18.706] Downloaded server infos in 772ms
[Debug - 15:07:18.708] GET 200 https://<some-corporate-server-url.com>/api/components/search.protobuf?qualifiers=TRK&ps=500&p=1 | response time=787ms
[Debug - 15:07:18.730] GET 200 https://<some-corporate-server-url.com>/api/authentication/validate?format=json | response time=21ms
...
```
Please, let me know if I can help you by adding more info. Should I close this issue or do I leave it to you?
Thank you.

**Comment by asmodeus812** [comment]
Great, I'm happy to hear it is working, i will close the issue, no problem.
